version: "3.9"
networks:
  call-for-paper-service:
    driver: bridge
volumes:
  postgres_data:
services:
  app:
    container_name: call-for-paper
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "80:80"
    networks:
      - call-for-paper-service
    depends_on: 
      - postgres_db
  postgres_db:
    container_name: task-postgres
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task-postgres
    ports:
      - "5432"
    networks:
      - call-for-paper-service
    volumes:
      - postgres_data:/var/lib/postgresql/data